apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml

images:
- name: 725288432775.dkr.ecr.us-east-1.amazonaws.com/guestbook
  newTag: 5dc0916c879efc1da74d24c5cb61611a7e5e4fd9
